version: '3'

services:
  php:
    build: ./php
    volumes:
       - ./php/php.ini:/usr/local/etc/php/php.ini
       - ./php/apache2.conf:/etc/apache2/apache2.conf
       - ./html:/var/www/html
    ports:
       - 80:80
  mysql:
    image: mysql:8.0
    volumes:
       - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 4040:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
  squid:
    build: ./squid
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/squid.conf:/etc/squid/squid.conf