version: '3'

services:
  php:
    build: ./php
    volumes:
       - ./php/php.ini:/usr/local/etc/php/php.ini
       - ./html:/var/www/html
    ports:
       - 80:80
  mysql:
    image: mysql:8.0
    volumes:
       - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 4040:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=test
      - PMA_PASSWORD=test

    